namespace RebuildUs.Enums;

public enum CustomRPC
{
    // Main Controls

    ResetVariables = 100,
    ShareOptions,
    ForceEnd,
    WorkaroundSetRoles,
    SetRole,
    SetModifier,
    VersionHandshake,
    UseUncheckedVent,
    UncheckedMurderPlayer,
    UncheckedCmdReportDeadBody,
    UncheckedExilePlayer,
    DynamicMapOption,
    SetGameStarting,
    ShareGamemode,
    StopStart,
    UncheckedSetTasks,

    // Role functionality
    EngineerFixLights,
    EngineerFixSubmergedOxygen,
    EngineerUsedRepair,
    CleanBody,
    SheriffKill,
    MedicSetShielded,
    ShieldedMurderAttempt,
    TimeMasterShield,
    TimeMasterRewindTime,
    ShifterShift,
    SwapperSwap,
    MorphingMorph,
    CamouflagerCamouflage,
    TrackerUsedTracker,
    VampireSetBitten,
    PlaceGarlic,
    JackalCreatesSidekick,
    SidekickPromotes,
    ErasePlayerRoles,
    SetFutureErased,
    SetFutureShifted,
    SetFutureShielded,
    SetFutureSpelled,
    PlaceNinjaTrace,
    PlacePortal,
    UsePortal,
    PlaceJackInTheBox,
    LightsOut,
    PlaceCamera,
    SealVent,
    ArsonistWin,
    GuesserShoot,
    LawyerSetTarget,
    LawyerPromotesToPursuer,
    SetBlanked,
    Bloody,
    SetFirstKill,
    Invert,
    SetTiebreak,
    SetInvisible,
    ThiefStealsRole,
    SetTrap,
    TriggerTrap,
    PlaceBomb,
    DefuseBomb,
    ShareRoom,
    YoyoMarkLocation,
    YoyoBlink,
    BreakArmor,
    SetLovers,
    SetShifterType,
    SwapperAnimate,

    // Other functionality
    ShareTimer,
    ShareGhostInfo,
    EventKick,
}